github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:    ["docker.io/paketobuildpacks/amazon-corretto", "gcr.io/paketo-buildpacks/amazon-corretto"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency:main
  with:
    glob:       amazon-corretto-[\d.-]+-linux-x64.tar.gz
    repository: corretto-8
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency:main
  with:
    glob:       amazon-corretto-[\d.-]+-linux-x64.tar.gz
    repository: corretto-11
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency:main
  with:
    glob:       amazon-corretto-[\d.-]+-linux-x64.tar.gz
    repository: corretto-17
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency:main
  with:
    glob:       amazon-corretto-[\d.-]+-linux-x64.tar.gz
    repository: corretto-21
- name:            JDK 22
  id:              jdk
  version_pattern: "22\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency:main
  with:
    glob:       amazon-corretto-[\d.-]+-linux-x64.tar.gz
    repository: corretto-22