# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Amazon Corretto implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/amazon-corretto"
  id = "paketo-buildpacks/amazon-corretto"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for Amazon Corretto"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/amazon-corretto/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update504:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:1.8.0:update504:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@8.0.492?arch=amd64"
    sha256 = "56f0f6ab9b50f69bdf72705542342c0ff9c4e0f531f03d6751dcebe164308983"
    source = "https://github.com/corretto/corretto-8/archive/refs/tags/8.504.01.1.tar.gz"
    source-sha256 = "fcbfda95e7db98bf1b19a81c0eafa92f70996a82d4cddb3a13dae39662a819ff"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/8.504.01.1/amazon-corretto-8.504.01.1-linux-x64.tar.gz"
    version = "8.0.504"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:11.0.32:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@11.0.32?arch=amd64"
    sha256 = "b09aac76316cef26dca770c89ca23ce55708bd0463e2640e86915ee528cb5bd0"
    source = "https://github.com/corretto/corretto-11/archive/refs/tags/11.0.32.9.1.tar.gz"
    source-sha256 = "0dd6a0428bfb9414070b6a4141afc6d8669a96bd55562451902dd72856553f11"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/11.0.32.9.1/amazon-corretto-11.0.32.9.1-linux-x64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:17.0.20:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@17.0.20?arch=amd64"
    sha256 = "74ff458657da91ca222681993e3c6b9a8e3629ca8e61c0d8cd90527280da9aa5"
    source = "https://github.com/corretto/corretto-17/archive/refs/tags/17.0.20.10.1.tar.gz"
    source-sha256 = "2c28bd04b13eb9b96d1b4538efa8e2d5543734c35cd0ed5fee0db7eb20229813"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/17.0.20.10.1/amazon-corretto-17.0.20.10.1-linux-x64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:21.0.12:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@21.0.12?arch=amd64"
    sha256 = "75faed442d38a89c27f920e45ab24f9f71ff8ca6b732bfea90cdb500decd3c6b"
    source = "https://github.com/corretto/corretto-21/archive/refs/tags/21.0.12.8.1.tar.gz"
    source-sha256 = "e14920233baca2000b21900852c66033c86b763126f6fc4323c7254f81edcac6"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/21.0.12.8.1/amazon-corretto-21.0.12.8.1-linux-x64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:25.0.4:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@25.0.4?arch=amd64"
    sha256 = "b838e42c8e915019ed34e4cc54c7cda2e7e00d2a2a49be44578814735fc9accc"
    source = "https://github.com/corretto/corretto-25/archive/refs/tags/25.0.4.8.1.tar.gz"
    source-sha256 = "c83515ba45fc6486e66b5d1b21d938095bbee2daad16f491b98a3531c010c668"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/25.0.4.8.1/amazon-corretto-25.0.4.8.1-linux-x64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:26.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@26.0.2?arch=amd64"
    sha256 = "f61206891b8e1009b117eefe38784cf31b0a5cdb02fd2e023556f436b85dedaa"
    source = "https://github.com/corretto/corretto-26/archive/refs/tags/26.0.2.11.1.tar.gz"
    source-sha256 = "4ba9f8d6c055205c11aa5f2b695429ecb711d6d632aaf6194e316612bd931428"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/26.0.2.11.1/amazon-corretto-26.0.2.11.1-linux-x64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update504:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:1.8.0:update504:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@8.0.492?arch=arm64"
    sha256 = "54d872a37ee35eafdf057ceb2dad2d25c250580db91e7a08f656c945d489a375"
    source = "https://github.com/corretto/corretto-8/archive/refs/tags/8.504.01.1.tar.gz"
    source-sha256 = "fcbfda95e7db98bf1b19a81c0eafa92f70996a82d4cddb3a13dae39662a819ff"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/8.504.01.1/amazon-corretto-8.504.01.1-linux-aarch64.tar.gz"
    version = "8.0.504"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:11.0.32:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@11.0.32?arch=arm64"
    sha256 = "5ee984d59dfc54fec798c908618c1b952622232d3b458a439b4ecfbc461cae5a"
    source = "https://github.com/corretto/corretto-11/archive/refs/tags/11.0.32.10.1.tar.gz"
    source-sha256 = "d0cb627df79f95e318ff33cc90a4e7bc1b166212bf3fc4dd71ee8a38675316fd"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/11.0.32.10.1/amazon-corretto-11.0.32.10.1-linux-aarch64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:17.0.20:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@17.0.20?arch=arm64"
    sha256 = "aca6cc93156f741995b81d91f2d7085992028b2c40056b5a405e6c7d9e350198"
    source = "https://github.com/corretto/corretto-17/archive/refs/tags/17.0.20.10.1.tar.gz"
    source-sha256 = "2c28bd04b13eb9b96d1b4538efa8e2d5543734c35cd0ed5fee0db7eb20229813"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/17.0.20.10.1/amazon-corretto-17.0.20.10.1-linux-aarch64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:21.0.12:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@21.0.12?arch=arm64"
    sha256 = "cda6f38775da6ba19e154dd2194a309dabfb12da87ad13f396893d9a555eb1ce"
    source = "https://github.com/corretto/corretto-21/archive/refs/tags/21.0.12.9.1.tar.gz"
    source-sha256 = "7f8820ca25965e2d12842d85e84a1c86334a6791ee1721a64ed4e7ffb7850409"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/21.0.12.9.1/amazon-corretto-21.0.12.9.1-linux-aarch64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:25.0.4:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@25.0.4?arch=arm64"
    sha256 = "d4acc8a6175d6aa98bb0c27ddaa138c68553ac6c097b57f417c38f536b414113"
    source = "https://github.com/corretto/corretto-25/archive/refs/tags/25.0.4.8.1.tar.gz"
    source-sha256 = "c83515ba45fc6486e66b5d1b21d938095bbee2daad16f491b98a3531c010c668"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/25.0.4.8.1/amazon-corretto-25.0.4.8.1-linux-aarch64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:amazon:corretto:26.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Corretto JDK"
    purl = "pkg:generic/amazon/corretto-jdk@26.0.2?arch=arm64"
    sha256 = "4427ec5b3697a5f4e7b0e988f0e7df4dcb4a4735c06fa52f770b87345e3b2929"
    source = "https://github.com/corretto/corretto-26/archive/refs/tags/26.0.2.11.1.tar.gz"
    source-sha256 = "4ba9f8d6c055205c11aa5f2b695429ecb711d6d632aaf6194e316612bd931428"
    stacks = ["*"]
    uri = "https://corretto.aws/downloads/resources/26.0.2.11.1/amazon-corretto-26.0.2.11.1-linux-aarch64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
